version: "3.9"
services:
  rumbledb:
    image: rumbledb/rumble:latest
    command: serve -p 8001 -h 0.0.0.0 # ["--shell yes"]
    volumes:
      - ./data:/data:ro
    ports:
      - "8001:8001"

  spark-master:
    image: bitnami/spark:3.5
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLE=no
      - SPARK_RPC_ENCRYPTION_ENABLE=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLE=no
      - SPARK_SSL_ENABLE=no
    ports:
      - "7077:7077"   # Spark master
      - "8080:8080"   # Master UI

  spark-worker:
    image: bitnami/spark:3.5
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"   # Worker UI

  hadoop-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-namenode
    environment:
      - CLUSTER_NAME=dotz
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./data:/host_data:ro
    ports:
      - "9870:9870"   # NameNode UI
      - "8020:8020"   # fs.defaultFS

  hadoop-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-datanode
    environment:
      - CLUSTER_NAME=dotz
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:8020
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    depends_on:
      - hadoop-namenode
    ports:
      - "9864:9864"   # DataNode UI

volumes:
  hadoop_namenode:
  hadoop_datanode:

